// <auto-generated />
using System;
using AgentopsServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentopsServer.Migrations
{
    [DbContext(typeof(AgentServerDbContext))]
    [Migration("20241016152057_UpdateAgentopsServerSchema")]
    partial class UpdateAgentopsServerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentopsServer.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("AgentId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AgentopsServer.Models.AgentSession", b =>
                {
                    b.Property<int>("AgentSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgentSessionId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("EndState")
                        .HasColumnType("text");

                    b.Property<string>("EndStateReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InitTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentSessionId");

                    b.ToTable("AgentSessions");
                });

            modelBuilder.Entity("AgentopsServer.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<DateTime>("InitTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AgentopsServer.Models.EventReturn", b =>
                {
                    b.Property<string>("EventReturnId")
                        .HasColumnType("text");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.HasKey("EventReturnId");

                    b.ToTable("EventReturns");
                });
#pragma warning restore 612, 618
        }
    }
}
